
#? Read FIle > mode="r" | Over write File > mode="w" | Add new text to File > mode="a"

#? Read File
# with open("my_file.txt") as file:
#     file_content = file.read()
#     print(file_content)

#? Over write file with new text
# with open("my_file.txt", mode="w") as file:
#     file.write("New Text which will delete previous text")

#? Add Text to existing File
# with open("my_file.txt", mode="a") as file:
#     file.write("\nHere is some new text")

#? Creating a new file using WRITE ("w") mode
with open("this_is_new_text_file.txt", mode="w") as file:
    file.write("I am being generated by code only")